# Generated by Django 5.0.6 on 2024-06-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serena_app', '0003_customer_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password2',
        ),
    ]
